define migrations skeleton
Vend-Dev/vend-backend pull request #5
Opened 2024-01-23 11:00 UTC by jahdevelops

2024-01-23 12:12 UTC, Lekejosh commented on src/controller/seller/order.controller.js
![image](https://github.com/Vend-Dev/vend-backend/assets/54216428/782f88c2-ea0b-4ea1-ace5-f5f94d707bb3)

Fix the errors

2024-01-23 12:13 UTC, Lekejosh commented on seeders/20240122220926-demo-flow.js
This is not working... Test and fix the errors

2024-01-24 10:39 UTC, Lekejosh commented
The new commits still has error expecially with the seeders file and no fix has been made to the order api route?

2024-01-24 17:14 UTC, jahdevelops commented on seeders/20240122220926-demo-flow.js
This has been fixed. The command has changed from `npm run seeders` to `npm run seed-mysql` [commit](https://github.com/Vend-Dev/vend-backend/pull/5/commits/192c96926ee838f4996b2964780679ec4273e0de)

2024-01-24 17:22 UTC, jahdevelops commented
The 

> The new commits still has error expecially with the seeders file and no fix has been made to the order api route?

This order api route had been fixed

2024-01-24 17:23 UTC, jahdevelops commented on src/controller/seller/order.controller.js
This order api routes has been fixed

2024-01-24 19:35 UTC, Lekejosh commented on src/controller/seller/order.controller.js
Did you test this route? It keeps returning empty array after successfully paying an Order

2024-01-24 19:39 UTC, Lekejosh commented on seeders/20240122220926-demo-flow.js
This fix here should be better than hard coding it and also run `npm rm uuid` to removed the unused package... Also Test this on your end

2024-01-24 19:44 UTC, Lekejosh commented on package.json
Test the seed-mysql fix on your end... This also uses the development mode to run

2024-01-24 19:44 UTC, Lekejosh requested changes
Check and fix the requested changes

2024-01-25 08:23 UTC, jahdevelops commented on seeders/20240122220926-demo-flow.js
The hardcoded uuids were just for development/testing the seeded models in integration with the routes, so you can easily copy the uuid from there and test the supposed route

2024-01-25 08:25 UTC, jahdevelops commented on src/controller/seller/order.controller.js
Changes has been made to the route, ensure `carts` attribute is saved as JSON when writing to the order model.

2024-01-25 09:17 UTC, Lekejosh approved these changes
Closing this pull request, but will still work on the order controller

2024-01-25 09:19 UTC, Lekejosh commented
Resolve the conflicts

2024-01-27 09:35 UTC, merged