Add routes and controllers for courier
Vend-Dev/vend-backend pull request #7
Opened 2024-01-31 16:28 UTC by jahdevelops

2024-02-01 00:24 UTC, Lekejosh commented on src/controller/auth.controller.js
Why adding role to login controller?

All users have there roles attached to them in the DB... No need to specifiy again... Fix your eslint errors

Did you disable husky on your end?

2024-02-01 00:27 UTC, Lekejosh commented on seeders/20240122220926-demo-flow.js
Fix duplicate email errors here

2024-02-01 00:28 UTC, Lekejosh commented on src/controller/Order/order.controller.js
Fix eslint errors here

2024-02-01 00:29 UTC, Lekejosh commented on src/controller/courier/order.controller.js
fix the unneccessary semicolon errors in all the files in your PR

2024-02-01 00:30 UTC, Lekejosh requested changes
Fix all the errors and check the comments made

2024-02-02 12:39 UTC, jahdevelops commented
Fix: Remove role auth from login route

2024-02-03 10:23 UTC, merged